### ISSUE TITLE
Release v1.0.0-beta.9

### ISSUE THREAD

**Issue by diafour** [flant/shell-operator#159]
Steps before release:
- [x] bump jq sources in libjq-go, because of https://github.com/flant/libjq-go/issues/10 (done in #163 )
- [x] export metrics for hooks #130 (ported from addon-operator in #165)
- [x]  #158 approbation in addon-operaton (https://github.com/flant/addon-operator/pull/107 merged, tested)
- [x] update shell-lib to use type: Group and type: Schedule #160 
- [x] `executeHookOnSynchronization` #162 (done in #164)

**Comment by diafour** [comment]
https://github.com/flant/shell-operator/releases/tag/v1.0.0-beta.9
